### PR TITLE
fix documentation

### PR DESCRIPTION
**Pull request by TannerGilbert**
Updated README.md and CONTRIBUTION.md,

- Updated links since the documentation for v1 was moved to http://fastai1.fast.ai/
- Updated installation to not install latest fastai version

### CODE REVIEW

**Comment by TannerGilbert** [comment]
Fixes #3

**Comment by jph00** [comment]
Great!

**Comment by TannerGilbert** [comment]
@jph00 is there still a Github action that builds the docs from the docs_src folder as described in the documentation or should I run it locally and then create a pull request?

**Comment by jph00** [comment]
Please run it locally and do a PR - thanks!

**Comment by TannerGilbert** [comment]
@jph00 Created new pr #4

**Pull request merged**
